export declare const createEvent: any;
export declare const addStaff: any;
export declare const rsvp: any;
export declare const counts: any;
export declare const publicView: any;
export declare const createOrg: any;
export declare const can: any;
export declare const roleOf: any;
export declare const ROLES: any;
export declare const GRANTS: any;
declare const _default: any;
export default _default;
